general:
  project_name: scembed_test_spatial
  mamba_env: scembed
  entity: spatial_vi
  modules: stack eth_proxy
  count: 1

slurm:
  time: "01:00:00"
  mem_per_cpu: "32G"
  job_name: scembed_scvi
  output: slurm_logs/scvi_%A_%a.out
  array: "0-3"
  gpus: rtx_4090:1

wandb:
  program: train.py
  method: grid
  name: scvi
  metric:
    goal: maximize
    name: scib_total_score
  parameters:
    method:
      value: scvi
    n_layers:
      values: [1, 2]
    batch_size:
      values: [512, 1024]
